version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webflow-swapcard"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l89u0zbwv2qf"
s3_prefix = "webflow-swapcard"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
