AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A crob job using AWS CloudWatch EventBridge that invokes a lambda function

Resources:
  CronJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/webflow
      Handler: webflow.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          SWAPCARD_PERSONAL_ACCESS_TOKEN: "NjI0NzUwN2JiMDJkOGQ0OGYzZjVlYzc4OjcyNDZlZDczYzI3MjRiZWZhMWM4NjM4NGI4MGU5YjE0"
          WEBFLOW_ACCESS_TOKEN: "640b4b84739a7765c30c39028f2beec09710d1a82e72315408b40f367d1ec84d"

      Events:
        CronJob:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
