const sujetMapping = {
  "developper-une-idee-dentreprise": "Développer une idée d’entreprise",
  "financer-une-idee": "Financer une idée",
  "passer-de-lidee-a-laction": "Passer de l’idée à l’action",
  "connecter-son-entreprise-aux-nouvelles-technologies":
    "Connecter son entreprise aux nouvelles technologies",
  "positionner-son-entreprise": "Positionner son entreprise",
  "gerer-son-entreprise": "Gérer son entreprise",
  financement: "Financement",
  assurances: "Assurances",
  environnement: "Environnement",
  repreneuriat: "Repreneuriat",
  commercialisation: "Commercialisation",
  marketing: "Marketing",
  innovation: "Innovation",
  association: "Association",
  comptabilite: "Comptabilité",
  droit: "Droit",
  ecologie: "Écologie",
  "economie-circulaire": "Économie circulaire",
  "economie-locale": "Économie locale",
  "economie-sociale": "Économie sociale",
  "ethique-et-technologie": "Éthique et technologie",
  export: "Export",
  fiscalite: "Fiscalité",
  "intelligence-artificielle": "Intelligence artificielle",
  ideation: "Idéation",
  "intelligence-economique": "Intelligence économique",
  investissement: "Investissement",
  "leadership-gestion": "Leadership / Gestion",
  "organisation-du-travail": "Organisation du travail",
  "penurie-de-main-doeuvre": "Pénurie de main d'oeuvre",
  prototypage: "Prototypage",
  "recherche-et-developpement": "Recherche et développement",
  "representativite-et-inclusion": "Représentativité et inclusion",
  "ressources-humaines": "Ressources humaines",
  "sante-mentale": "Santé mentale",
  "solutions-informatiques": "Solutions informatiques",
  "strategie-numerique": "Stratégie numérique",
  ventes: "Ventes"
};

module.exports = {
  sujetMapping
};
