const sujetMapping = {
	financement: "Financement",
	assurances: "Assurances",
	environnement: "Environnement",
	repreneuriat: "Repreneuriat",
	commercialisation: "Commercialisation",
	marketing: "Marketing",
	innovation: "Innovation",
	association: "Association",
	comptabilite: "Comptabilité",
	droit: "Droit",
	ecologie: "Écologie",
	"economie-circulaire": "Economie circulaire",
	"economie-locale": "Économie locale",
	"economie-sociale": "Économie sociale",
	"ethique-et-technologie": "Ethique et technologie",
	export: "Export",
	fiscalite: "Fiscalité",
	"intelligence-artificielle": "Intelligence artificielle",
	ideation: "Idéation",
	"intelligence-economique": "Intelligence économique",
	investissement: "Investissement",
	"leadership-gestion": "Leadership / Gestion",
	"organisation-du-travail": "Organisation du travail",
	"penurie-de-main-doeuvre": "Pénurie de main d'oeuvre",
	prototypage: "Prototypage",
	"recherche-et-developpement": "Recherche et développement",
	"representativite-et-inclusion": "Représentativité et inclusion",
	"ressources-humaines": "Ressources humaines",
	"sante-mentale": "Santé mentale",
	"solutions-informatiques": "Solutions informatiques",
	"strategie-numerique": "Stratégie numérique",
	ventes: "Ventes",
};

module.exports = {
	sujetMapping,
};
